/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CircularChart {
        "data": string;
        "header": string;
        "height": number;
        "label": string;
        "type": string;
        "width": number;
    }
    interface CircularPieChart {
        "data": string;
        "height": number;
        "valueType": string;
        "width": number;
    }
    interface LineChart {
        "data": string;
        "height": number;
        "width": number;
    }
}
declare global {
    interface HTMLCircularChartElement extends Components.CircularChart, HTMLStencilElement {
    }
    var HTMLCircularChartElement: {
        prototype: HTMLCircularChartElement;
        new (): HTMLCircularChartElement;
    };
    interface HTMLCircularPieChartElement extends Components.CircularPieChart, HTMLStencilElement {
    }
    var HTMLCircularPieChartElement: {
        prototype: HTMLCircularPieChartElement;
        new (): HTMLCircularPieChartElement;
    };
    interface HTMLLineChartElement extends Components.LineChart, HTMLStencilElement {
    }
    var HTMLLineChartElement: {
        prototype: HTMLLineChartElement;
        new (): HTMLLineChartElement;
    };
    interface HTMLElementTagNameMap {
        "circular-chart": HTMLCircularChartElement;
        "circular-pie-chart": HTMLCircularPieChartElement;
        "line-chart": HTMLLineChartElement;
    }
}
declare namespace LocalJSX {
    interface CircularChart {
        "data"?: string;
        "header"?: string;
        "height"?: number;
        "label"?: string;
        "type"?: string;
        "width"?: number;
    }
    interface CircularPieChart {
        "data"?: string;
        "height"?: number;
        "valueType"?: string;
        "width"?: number;
    }
    interface LineChart {
        "data"?: string;
        "height"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "circular-chart": CircularChart;
        "circular-pie-chart": CircularPieChart;
        "line-chart": LineChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "circular-chart": LocalJSX.CircularChart & JSXBase.HTMLAttributes<HTMLCircularChartElement>;
            "circular-pie-chart": LocalJSX.CircularPieChart & JSXBase.HTMLAttributes<HTMLCircularPieChartElement>;
            "line-chart": LocalJSX.LineChart & JSXBase.HTMLAttributes<HTMLLineChartElement>;
        }
    }
}
