/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CircularChart {
        "data": string;
        "height": number;
        "label": string;
        "type": string;
        "width": number;
    }
}
declare global {
    interface HTMLCircularChartElement extends Components.CircularChart, HTMLStencilElement {
    }
    var HTMLCircularChartElement: {
        prototype: HTMLCircularChartElement;
        new (): HTMLCircularChartElement;
    };
    interface HTMLElementTagNameMap {
        "circular-chart": HTMLCircularChartElement;
    }
}
declare namespace LocalJSX {
    interface CircularChart {
        "data"?: string;
        "height"?: number;
        "label"?: string;
        "type"?: string;
        "width"?: number;
    }
    interface IntrinsicElements {
        "circular-chart": CircularChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "circular-chart": LocalJSX.CircularChart & JSXBase.HTMLAttributes<HTMLCircularChartElement>;
        }
    }
}
